### ISSUE TITLE
Can't Store Vehicle

### ISSUE THREAD

**Issue by NazriGenfil** [WRSmp4/esx_garage-master#1]
hello I used your script for a long time, before it was normal I could enter the car but when GTA 5 updated the new map I could not enter the car anymore, I know this problem is in + set sv_enforceGameBuild 2189 (to bring up a new map) but I don't know how to fix it
btw + set sv_enforceGameBuild 2189 can only be used on artifacts 3352 and above

this the error
![image](https://user-images.githubusercontent.com/40690481/104586395-fecf9700-5697-11eb-9d73-e94e901b0476.png)

and this my txadmin setting
![image](https://user-images.githubusercontent.com/40690481/104586477-1870de80-5698-11eb-8116-c173af5c4595.png)

Hope you can help me :)

**Comment by WRSmp4** [comment]
Hey !
Thank you for using my script !
Don't worry about, i'll do a v2 soon!
Have a nice day

**Comment by NazriGenfil** [comment]
Thanks, I'll be waiting for it
